In [38]:
import pandas as pd
import numpy as np
# from keras import *
from sklearn.linear_model import LogisticRegression
import statsmodels.api as sm 
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.metrics import (confusion_matrix,  
                           accuracy_score)

/Users/aruba/anaconda3/lib/python3.7/site-packages/statsmodels/compat/pandas.py:23: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  data_klasses = (pandas.Series, pandas.DataFrame, pandas.Panel)

In [763]:
pd.read_csv("Data/2020_LoL_esports_match_data_from_OraclesElixir_20201129.csv")

0         top
1         jng
2         mid
3         bot
4         sup
         ...
77419     mid
77420     bot
77421     sup
77422    team
77423    team
Name: position, Length: 77424, dtype: object

In [515]:
df = pd.read_csv("Data/team_merge.csv")
df = df.iloc[:,2:]
df

,b_result,b_kills,b_deaths,b_assists,b_doublekills,b_triplekills,b_quadrakills,b_pentakills,b_firstblood,b_team_kpm,...,r_gspd,r_monsterkills,r_monsterkillsownjungle,r_monsterkillsenemyjungle,r_goldat10,r_xpat10,r_csat10,r_goldat15,r_xpat15,r_csat15
0,0,4,11,13,0,0,0,0,1,0.1281,...,0.015512,178,116,18,14859,17500,322,23344,28172,509
1,1,20,4,44,3,1,1,1,1,0.8602,...,-0.249167,103,96,0,14138,17184,302,22121,27498,473
2,0,14,25,27,1,0,0,0,0,0.4461,...,0.078106,222,155,17,16737,18076,296,25885,30159,481
3,1,35,25,69,7,2,1,0,0,0.9677,...,-0.129263,217,157,4,16042,16881,289,25213,27487,445
4,0,7,23,15,0,0,0,0,0,0.2093,...,0.090242,250,159,32,16640,19669,333,26142,30353,512
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6364,0,9,16,23,0,0,0,0,0,0.2975,...,0.014583,157,100,13,15309,17325,292,24412,28090,458
6365,1,13,7,34,1,0,0,0,0,0.4424,...,-0.119099,168,109,16,15709,16975,282,24242,28071,472
6366,1,19,9,30,2,0,0,0,0,0.7792,...,-0.266169,107,79,4,16518,17009,285,25201,26997,430
6367,0,2,17,7,0,0,0,0,0,0.0892,...,0.161670,180,74,47,14905,19014,350,25931,30589,499
6368,1,25,22,43,3,1,0,0,1,0.8069,...,0.048376,220,125,45,15359,18009,300,26282,29764,464

In [516]:
# pd.DataFrame(df.groupby("champion").mean()['result'].sort_values(ascending = False)).head(20)

In [517]:
# pd.DataFrame(df.groupby("champion").count()['result'].sort_values(ascending = False)).head(20)

In [692]:
df.columns

Index(['b_result', 'b_kills', 'b_deaths', 'b_assists', 'b_doublekills',
       'b_triplekills', 'b_quadrakills', 'b_pentakills', 'b_firstblood',
       'b_team_kpm',
       ...
       'r_gspd', 'r_monsterkills', 'r_monsterkillsownjungle',
       'r_monsterkillsenemyjungle', 'r_goldat10', 'r_xpat10', 'r_csat10',
       'r_goldat15', 'r_xpat15', 'r_csat15'],
      dtype='object', length=102)

In [693]:
A	Total assists
AGT	Average game time/duration, in minutes
APG	Assists per game
B%	Percentage of games in which the champion was banned (not tied to a specific role)
BN%	Baron control rate
CCPM	Crowd control dealt to champions per minute
Champion	Champion name
CKPM	Average combined kills per minute (team kills + opponent kills)
CS%P15	Average share of team's total CS post-15-minutes
CSD10	Average creep score difference at 10 minutes
CSD15	Average creep score difference at 15 minutes
CSD20	Average creep score difference at 20 minutes
CSPM	Average monsters + minions killed per minute
CTR%	Counter-pick rate: percentage of games in which this player/champion was picked after their lane opponent (not always available)
CWPM	Control wards purchased per minute
D	Total deaths
DMG%	Damage Share: average share of team’s total damage to champions
DPG	Deaths per game
DPM	Average damage to champions per minute
DRG%	Dragon control rate: percent of all Dragons killed that were taken by the team, reflecting only elemental drakes if ELD% is present
DTH%	Average share of team’s deaths
EGPM	Average earned gold per minute (excludes starting gold and inherent gold generation)
EGR	Early-Game Rating
ELD%	Elder dragon control rate
F3T%	First-to-three-towers rate (percentage of games in which team was the first to 3 tower kills
FB%	First Blood rate -- for players/champions, percent of games earning a First Blood participation (kill or assist)
FBN%	First Baron rate
FBV%	First Blood Victim rate -- percent of games player/champion was killed for First Blood
FD%	First dragon rate
FT%	First tower rate
GD10	Average gold difference at 10 minutes
GD15	Average gold difference at 15 minutes
GD20	Average gold difference at 20 minutes
GOLD%	Gold Share: average share of team’s total gold earned (excludes starting gold and inherent gold generation)
GP	Games Played
GPM	Average gold per minute
GPR	Gold percent rating (average amount of game’s total gold held, relative to 50%)
GSPD	Average gold spent percentage difference
GXD10	Average gold+experience difference at 10 minutes
GXD15	Average gold+experience difference at 15 minutes
GXD20	Average gold+experience difference at 20 minutes
HLD%	Rift Herald control rate
IWC%	Average percentage of opponent’s invisible wards cleared
JNG%	Jungle Control: average share of game’s total jungle CS
K	Total kills
KD	Kill-to-Death Ratio
KDA	Total Kill/Death/Assist ratio
KP	Kill participation: percentage of team's kills in which player earned a Kill or Assist
KPG	Kills per game
KS%	Kill share: player's percentage of their team's total kills
L	Losses
LNE%	Lane Control: average share of game’s total lane CS
MLR	Mid/Late Rating
P%	Percentage of games champion was picked in this role.
P+B%	Percentage of games in which the champion was either banned or picked in any role
Player	Player's in-game name
Pos	Position
Team	Team name
VSPM	Vision score per minute
VWC%	Average percentage of opponent’s visible wards cleared
W	Wins
W%	Win percentage
WC%	Average percentage of opponent wards cleared
WCPM	Average wards cleared per minute
WPM	Average wards placed per minute
XPD10	Average experience difference at 10 minutes
XPD15	Average experience difference at 15 minutes
XPD20	Average experience difference at 20 minutes

### Feature Selection

In [520]:
df = df.apply(lambda x: x.fillna(x.mean()),axis=0)
df = df.dropna(axis=1)
df.columns

Index(['b_result', 'b_kills', 'b_deaths', 'b_assists', 'b_doublekills',
       'b_triplekills', 'b_quadrakills', 'b_pentakills', 'b_firstblood',
       'b_team_kpm',
       ...
       'r_gspd', 'r_monsterkills', 'r_monsterkillsownjungle',
       'r_monsterkillsenemyjungle', 'r_goldat10', 'r_xpat10', 'r_csat10',
       'r_goldat15', 'r_xpat15', 'r_csat15'],
      dtype='object', length=102)

In [699]:
y = df['b_result']
X = df.drop(columns = 'b_result')
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1, shuffle = True)
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.2, random_state=1, shuffle = True)

In [698]:
X_train

,b_kills,b_deaths,b_assists,b_doublekills,b_triplekills,b_quadrakills,b_pentakills,b_firstblood,b_team_kpm,b_ckpm,...,r_gspd,r_monsterkills,r_monsterkillsownjungle,r_monsterkillsenemyjungle,r_goldat10,r_xpat10,r_csat10,r_goldat15,r_xpat15,r_csat15
2434,12,20,32,0,0,0,0,0,0.3631,0.9682,...,0.196172,183,116,15,16695,19274,346,26367,28351,477
4993,19,8,35,3,0,0,0,1,0.6408,0.9106,...,-0.081562,194,161,5,15686,19282,338,24274,30168,528
1358,20,12,33,4,0,0,0,1,0.5403,0.8645,...,0.011155,329,231,25,15381,19451,350,25219,32862,523
2356,12,12,28,0,0,0,0,1,0.3148,0.6296,...,0.019616,280,182,41,15116,18923,333,23799,30265,541
1876,17,6,37,1,0,0,0,1,0.4713,0.6377,...,-0.068693,151,119,0,14155,17062,291,22000,27152,464
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5023,7,13,13,1,0,0,0,0,0.1764,0.5040,...,0.015555,323,193,39,16867,17712,307,27716,28845,513
363,17,6,42,3,0,0,0,1,0.5534,0.7488,...,-0.063824,184,143,1,15251,19182,338,23234,29938,525
6210,15,6,32,2,2,1,1,0,0.5122,0.7171,...,-0.070261,167,118,8,14731,17012,295,23113,27862,503
4562,5,0,8,0,0,0,0,1,0.1777,0.1777,...,-0.165564,163,125,12,15106,18868,345,22933,29566,536
2038,12,3,27,1,0,0,0,1,0.3768,0.4710,...,-0.155080,156,126,5,14649,17838,316,21564,27787,487

In [261]:
X_train.columns

Index(['side', 'assists', 'teamkills', 'teamdeaths', 'doublekills',
       'triplekills', 'quadrakills', 'pentakills', 'firstblood', 'team kpm',
       'ckpm', 'firstdragon', 'dragons', 'opp_dragons', 'elementaldrakes',
       'opp_elementaldrakes', 'infernals', 'mountains', 'clouds', 'oceans',
       'dragons (type unknown)', 'elders', 'opp_elders', 'firstherald',
       'heralds', 'opp_heralds', 'firstbaron', 'barons', 'opp_barons',
       'firsttower', 'towers', 'opp_towers', 'firstmidtower',
       'firsttothreetowers', 'inhibitors', 'opp_inhibitors',
       'damagetochampions', 'dpm', 'damagetakenperminute',
       'damagemitigatedperminute', 'wardsplaced', 'wpm', 'wardskilled', 'wcpm',
       'controlwardsbought', 'visionscore', 'vspm', 'totalgold', 'earnedgold',
       'earned gpm', 'goldspent', 'gspd', 'total cs', 'minionkills',
       'monsterkills', 'monsterkillsownjungle', 'monsterkillsenemyjungle',
       'cspm', 'goldat10', 'xpat10', 'csat10', 'opp_goldat10', 'opp_xpat10',
       'opp_csat10', 'golddiffat10', 'xpdiffat10', 'csdiffat10', 'goldat15',
       'xpat15', 'csat15', 'opp_goldat15', 'opp_xpat15', 'opp_csat15',
       'golddiffat15', 'xpdiffat15', 'csdiffat15'],
      dtype='object')

#### SVM

In [700]:
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC

grid_c = {0.001:0,0.01:0,0.1:0,1:0,10:0,100:0,1000:0}
for c in grid_c.keys():
    svm = make_pipeline(StandardScaler(), SVC(gamma='auto',C = c, kernel = 'rbf'))
    svm.fit(X_train, y_train)
    prediction = list(map(round,svm.predict(X_val)))
    acc = accuracy_score(y_val, prediction)
    grid_c[c] = acc
dict(sorted(grid_c.items(), key=lambda item: item[1],reverse = True))

In [701]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1, shuffle = True)
svm = make_pipeline(StandardScaler(), SVC(gamma='auto',C = 10, kernel = 'rbf'))
svm.fit(X_train, y_train)
prediction = list(map(round,svm.predict(X_test)))
cm = confusion_matrix(y_test, prediction)  
print ("Confusion Matrix : \n", cm)  
  
# accuracy score of the model 
print('Test accuracy = ', accuracy_score(y_test, prediction))

{10: 0.9970559371933267,
 100: 0.9970559371933267,
 1000: 0.9970559371933267,
 1: 0.9960745829244357,
 0.1: 0.9931305201177625,
 0.01: 0.9764474975466143,
 0.001: 0.5269872423945045}

#### KNN

In [718]:
from sklearn.neighbors import KNeighborsClassifier
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1, shuffle = True)
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.2, random_state=1, shuffle = True)
grid_neigh = {i:0 for i in range(1,21)}
for key in grid_neigh.keys():
    neigh = make_pipeline(StandardScaler(), KNeighborsClassifier(n_neighbors=key))
    neigh.fit(X_train, y_train)
    prediction = list(map(round,neigh.predict(X_val)))
    acc = accuracy_score(y_val, prediction)
    grid_neigh[key] = acc
dict(sorted(grid_neigh.items(), key=lambda item: item[1],reverse = True))

In [719]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1, shuffle = True)

neigh = make_pipeline(StandardScaler(), KNeighborsClassifier(n_neighbors=5))
neigh.fit(X_train, y_train)
prediction = list(map(round,neigh.predict(X_test)))

cm = confusion_matrix(y_test, prediction)  
print ("Confusion Matrix : \n", cm)  
  
# accuracy score of the model 
print('Test accuracy = ', accuracy_score(y_test, prediction))

{5: 0.9842983316977428,
 9: 0.9833169774288518,
 17: 0.9823356231599607,
 18: 0.9823356231599607,
 19: 0.9813542688910697,
 20: 0.9813542688910697,
 6: 0.9803729146221786,
 7: 0.9803729146221786,
 16: 0.9803729146221786,
 3: 0.9793915603532876,
 10: 0.9793915603532876,
 11: 0.9793915603532876,
 15: 0.9793915603532876,
 8: 0.9784102060843964,
 12: 0.9784102060843964,
 13: 0.9774288518155054,
 14: 0.9774288518155054,
 4: 0.9754661432777233,
 2: 0.9676153091265947,
 1: 0.9666339548577036}

### Neural Network

In [722]:
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers import Dropout
import keras
from keras import backend as K

In [723]:
X.shape

(6369, 101)

In [737]:
from keras.models import Sequential
from keras.layers import Dense
from keras.callbacks import EarlyStopping
K.clear_session()
model = Sequential()
model.add(Dense(16, input_dim=X.shape[1], activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
# compile the keras model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
es = EarlyStopping(monitor='val_loss', mode='min', verbose=1,patience = 10)
# fit the keras model on the dataset
model.fit(X_train, y_train, epochs=50, batch_size=10,callbacks=[es],validation_split=0.2)
# evaluate the keras model
_, accuracy = model.evaluate(X_test, y_test)
print('Test Set Accuracy: %.2f' % (accuracy*100))

Epoch 1/50
408/408 [==============================] - 0s 1ms/step - loss: 555.2491 - accuracy: 0.8246 - val_loss: 15.6624 - val_accuracy: 0.8852
Epoch 2/50
408/408 [==============================] - 0s 878us/step - loss: 10.0858 - accuracy: 0.9053 - val_loss: 4.4847 - val_accuracy: 0.9382
Epoch 3/50
408/408 [==============================] - 0s 891us/step - loss: 8.0219 - accuracy: 0.8960 - val_loss: 19.2397 - val_accuracy: 0.7763
Epoch 4/50
408/408 [==============================] - 0s 881us/step - loss: 5.8105 - accuracy: 0.9151 - val_loss: 3.4653 - val_accuracy: 0.9352
Epoch 5/50
408/408 [==============================] - 0s 868us/step - loss: 7.2552 - accuracy: 0.9046 - val_loss: 2.3476 - val_accuracy: 0.9549
Epoch 6/50
408/408 [==============================] - 0s 876us/step - loss: 4.5702 - accuracy: 0.9259 - val_loss: 1.9125 - val_accuracy: 0.9627
Epoch 7/50
408/408 [==============================] - 0s 900us/step - loss: 2.9180 - accuracy: 0.9470 - val_loss: 1.1643 - val_accuracy: 0.9676
Epoch 8/50
408/408 [==============================] - 0s 882us/step - loss: 3.0706 - accuracy: 0.9438 - val_loss: 2.1916 - val_accuracy: 0.9519
Epoch 9/50
408/408 [==============================] - 0s 878us/step - loss: 2.8162 - accuracy: 0.9512 - val_loss: 0.9113 - val_accuracy: 0.9755
Epoch 10/50
408/408 [==============================] - 0s 880us/step - loss: 2.2531 - accuracy: 0.9607 - val_loss: 0.5366 - val_accuracy: 0.9823
Epoch 11/50
408/408 [==============================] - 0s 882us/step - loss: 1.6793 - accuracy: 0.9664 - val_loss: 8.4408 - val_accuracy: 0.8685
Epoch 12/50
408/408 [==============================] - 0s 888us/step - loss: 2.4798 - accuracy: 0.9603 - val_loss: 4.4206 - val_accuracy: 0.9264
Epoch 13/50
408/408 [==============================] - 0s 871us/step - loss: 1.9990 - accuracy: 0.9674 - val_loss: 0.5850 - val_accuracy: 0.9833
Epoch 14/50
408/408 [==============================] - 0s 954us/step - loss: 1.7042 - accuracy: 0.9733 - val_loss: 0.8784 - val_accuracy: 0.9823
Epoch 15/50
408/408 [==============================] - 0s 1000us/step - loss: 1.7279 - accuracy: 0.9735 - val_loss: 0.4961 - val_accuracy: 0.9872
Epoch 16/50
408/408 [==============================] - 0s 858us/step - loss: 1.2374 - accuracy: 0.9742 - val_loss: 3.0621 - val_accuracy: 0.9509
Epoch 17/50
408/408 [==============================] - 0s 890us/step - loss: 1.2961 - accuracy: 0.9718 - val_loss: 3.9992 - val_accuracy: 0.9392
Epoch 18/50
408/408 [==============================] - 0s 901us/step - loss: 2.2696 - accuracy: 0.9642 - val_loss: 4.8240 - val_accuracy: 0.9392
Epoch 19/50
408/408 [==============================] - 0s 873us/step - loss: 1.3327 - accuracy: 0.9752 - val_loss: 0.3280 - val_accuracy: 0.9902
Epoch 20/50
408/408 [==============================] - 0s 893us/step - loss: 1.9924 - accuracy: 0.9681 - val_loss: 0.3472 - val_accuracy: 0.9892
Epoch 21/50
408/408 [==============================] - 0s 865us/step - loss: 1.9008 - accuracy: 0.9733 - val_loss: 8.6869 - val_accuracy: 0.8970
Epoch 22/50
408/408 [==============================] - 0s 883us/step - loss: 2.2466 - accuracy: 0.9693 - val_loss: 0.7647 - val_accuracy: 0.9823
Epoch 23/50
408/408 [==============================] - 0s 907us/step - loss: 1.3829 - accuracy: 0.9774 - val_loss: 0.5902 - val_accuracy: 0.9853
Epoch 24/50
408/408 [==============================] - 0s 881us/step - loss: 1.6160 - accuracy: 0.9737 - val_loss: 1.0806 - val_accuracy: 0.9755
Epoch 25/50
408/408 [==============================] - 0s 868us/step - loss: 1.5190 - accuracy: 0.9764 - val_loss: 0.4275 - val_accuracy: 0.9892
Epoch 26/50
408/408 [==============================] - 0s 897us/step - loss: 0.6616 - accuracy: 0.9828 - val_loss: 0.3027 - val_accuracy: 0.9902
Epoch 27/50
408/408 [==============================] - 0s 852us/step - loss: 3.5996 - accuracy: 0.9647 - val_loss: 1.9284 - val_accuracy: 0.9686
Epoch 28/50
408/408 [==============================] - 0s 879us/step - loss: 1.3708 - accuracy: 0.9804 - val_loss: 0.4534 - val_accuracy: 0.9902
Epoch 29/50
408/408 [==============================] - 0s 897us/step - loss: 1.2908 - accuracy: 0.9806 - val_loss: 0.6196 - val_accuracy: 0.9853
Epoch 30/50
408/408 [==============================] - 0s 884us/step - loss: 1.0178 - accuracy: 0.9816 - val_loss: 0.6567 - val_accuracy: 0.9823
Epoch 31/50
408/408 [==============================] - 0s 883us/step - loss: 1.7557 - accuracy: 0.9708 - val_loss: 0.4571 - val_accuracy: 0.9892
Epoch 32/50
408/408 [==============================] - 0s 896us/step - loss: 0.8424 - accuracy: 0.9836 - val_loss: 0.5871 - val_accuracy: 0.9833
Epoch 33/50
408/408 [==============================] - 0s 893us/step - loss: 2.0297 - accuracy: 0.9745 - val_loss: 0.5821 - val_accuracy: 0.9853
Epoch 34/50
408/408 [==============================] - 0s 892us/step - loss: 1.6861 - accuracy: 0.9755 - val_loss: 0.5530 - val_accuracy: 0.9892
Epoch 35/50
408/408 [==============================] - 0s 899us/step - loss: 1.0306 - accuracy: 0.9818 - val_loss: 0.4269 - val_accuracy: 0.9863
Epoch 36/50
408/408 [==============================] - 0s 884us/step - loss: 0.7311 - accuracy: 0.9833 - val_loss: 0.5588 - val_accuracy: 0.9843
Epoch 00036: early stopping
40/40 [==============================] - 0s 585us/step - loss: 0.7974 - accuracy: 0.9874
Test Set Accuracy: 98.74

In [738]:
prediction = model.predict_classes(X_test)
cm = confusion_matrix(y_test, prediction) 
print ("Confusion Matrix : \n", cm)  
  
# accuracy score of the model 
print('Test accuracy = ', accuracy_score(y_test, prediction))

Confusion Matrix :
 [[570  13]
 [  3 688]]
Test accuracy =  0.9874411302982732

## Predict By Cluster

## 20 Cluster

In [525]:
cluster = pd.read_csv("cluster_winloss.csv").set_index('champion').drop(columns = "Unnamed: 0")

In [526]:
cluster['cluster']==19

champion
Karma       False
Nocturne    False
Lucian      False
Olaf        False
Fizz        False
            ...
Shaco       False
Teemo       False
Warwick     False
Rammus      False
Annie       False
Name: cluster, Length: 147, dtype: bool

In [527]:
for i in range(21):
    print(f"The Champions in Cluster {i} are:", cluster[cluster['cluster']==i].index.values)

The Champions in Cluster 0 are: ['Senna' 'Twitch' 'Jinx' 'Taliyah' 'Vayne']
The Champions in Cluster 1 are: ['Karma' 'Lux' 'Nunu & Willump' 'Volibear' 'Xin Zhao' 'Bard' 'Blitzcrank'
 'Morgana' 'Soraka']
The Champions in Cluster 2 are: ['Fiora' 'Irelia' 'Twisted Fate' 'Jax' 'Riven' 'Tristana' 'Tryndamere'
 'Camille' 'Aatrox']
The Champions in Cluster 3 are: ['Jayce' 'Quinn' 'Corki' 'Zoe' 'Vladimir' 'Syndra' 'Rumble' 'LeBlanc'
 "Vel'Koz" 'Viktor' 'Swain']
The Champions in Cluster 4 are: ['Thresh' 'Trundle' 'Skarner' 'Lulu' 'Jarvan IV' 'Taric' 'Leona'
 'Tahm Kench']
The Champions in Cluster 5 are: ['Sejuani' 'Pyke' 'Lee Sin' "Rek'Sai"]
The Champions in Cluster 6 are: ['Lucian' 'Dr. Mundo' 'Talon' 'Akali' 'Ekko' 'Aurelion Sol' 'Diana'
 'Yorick' 'Cassiopeia' 'Sylas' 'Ahri' 'Ryze' 'Qiyana' 'Orianna' "Cho'Gath"]
The Champions in Cluster 7 are: ['Sivir' 'Varus' 'Caitlyn' 'Aphelios']
The Champions in Cluster 8 are: ['Malphite' 'Mordekaiser' 'Gnar' 'Neeko' 'Yuumi' 'Singed' 'Lissandra'
 'Fiddlesticks' 'Zilean' 'Kennen' 'Maokai' 'Malzahar']
The Champions in Cluster 9 are: ['Zyra' 'Karthus' 'Xerath' 'Heimerdinger' 'Ziggs' 'Illaoi']
The Champions in Cluster 10 are: ['Sion' 'Urgot' 'Kled' 'Shen' 'Ornn' 'Renekton' 'Galio' 'Poppy' 'Wukong'
 'Darius' 'Sett']
The Champions in Cluster 11 are: ['Draven' 'Miss Fortune' 'Ashe' 'Jhin' "Kai'Sa" 'Kalista' 'Xayah']
The Champions in Cluster 12 are: ['Janna' 'Vi' 'Anivia' 'Sona']
The Champions in Cluster 13 are: ['Garen']
The Champions in Cluster 14 are: ['Gangplank' 'Evelynn' 'Azir' 'Lillia' 'Zed' 'Kayle']
The Champions in Cluster 15 are: ['Nocturne' 'Olaf' 'Fizz' 'Zac' 'Yasuo' 'Hecarim' 'Pantheon']
The Champions in Cluster 16 are: ['Veigar' 'Kassadin']
The Champions in Cluster 17 are: ["Kha'Zix" 'Graves' 'Nidalee' 'Gragas' 'Kayn' 'Elise' 'Kindred']
The Champions in Cluster 18 are: ["Kog'Maw" 'Shyvana' 'Ezreal']
The Champions in Cluster 19 are: ['Alistar' 'Rakan' 'Ivern' 'Braum' 'Nami' 'Nautilus']
The Champions in Cluster 20 are: ['Master Yi' 'Rengar' 'Amumu' 'Brand' 'Katarina' 'Shaco' 'Teemo' 'Warwick'
 'Rammus' 'Annie']

In [529]:
# df1 = df.iloc[:,10:]
# df1['result']

In [384]:
pick_columns = [f"pick{i}" for i in range(1,11)]
ban_columns = [f"ban{i}" for i in range(1,6)]
pick_columns.extend(ban_columns)
pick_columns.append('result')
pick_columns

['pick1',
 'pick2',
 'pick3',
 'pick4',
 'pick5',
 'pick6',
 'pick7',
 'pick8',
 'pick9',
 'pick10',
 'ban1',
 'ban2',
 'ban3',
 'ban4',
 'ban5',
 'result']

In [392]:
df_champion = pd.DataFrame(columns = pick_columns,index = [0])
df_champion

,pick1,pick2,pick3,pick4,pick5,pick6,pick7,pick8,pick9,pick10,ban1,ban2,ban3,ban4,ban5,result
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [393]:
df_champion = pd.DataFrame(columns = pick_columns,index = [0])
df1 = df.iloc[:,10:]
pick_dict = {f"pick{i}":0 for i in range(1,11)}
pick_dict['result'] = 0 # result = 1 means The first 5 champions wins (Blue Side)
pick_dict['ban1']=0
pick_dict['ban2']=0
pick_dict['ban3']=0
pick_dict['ban4']=0
pick_dict['ban5']=0
total_matchs = 6452 # len(df)/12
game_id = 1
idx = 0
while game_id <= total_matchs:
    for i in range(10):
#         print(df1.iloc[i,:])
        pick_dict[f'pick{i+1}'] = df1.iloc[i,:]['champion']
    for i in range(5):
        pick_dict[f'ban{i+1}'] = df1.iloc[11:12,6+i].values
    pick_dict['result'] = df1.iloc[0,:]['result']
    pick_df = pd.DataFrame(pick_dict,index=[game_id])
    idx += 12    
    game_id +=1
    df_champion = df_champion.append(pick_df,ignore_index = True)
    df1 = df1.iloc[12:]

In [626]:
df_banpick = pd.read_csv("Data/ban_pick_result.csv").set_index("Unnamed: 0")
df_banpick

,pick1,pick2,pick3,pick4,pick5,pick6,pick7,pick8,pick9,pick10,ban1,ban2,ban3,ban4,ban5,result
Unnamed: 0,,,,,,,,,,,,,,,,
1,Rumble,Elise,Qiyana,Miss Fortune,Nautilus,Aatrox,Gragas,Mordekaiser,Xayah,Rakan,Lucian,Akali,Lee Sin,Olaf,Jarvan IV,1
2,Jayce,Jarvan IV,Orianna,Miss Fortune,Nautilus,Aatrox,Elise,Qiyana,Varus,Tahm Kench,Lucian,Akali,Rek'Sai,Irelia,Camille,0
3,Renekton,Rek'Sai,Mordekaiser,Xayah,Rakan,Aatrox,Sejuani,Azir,Miss Fortune,Nautilus,Lucian,Akali,Elise,Irelia,Orianna,1
4,Pantheon,Elise,Nautilus,Xayah,Rakan,Quinn,Olaf,Orianna,Miss Fortune,Leona,Lucian,Rek'Sai,Akali,Renekton,Qiyana,0
5,Mordekaiser,Jarvan IV,Ryze,Xayah,Rakan,Renekton,Elise,Vel'Koz,Varus,Braum,Miss Fortune,Akali,Lucian,Lee Sin,Rumble,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6448,Akali,Hecarim,Irelia,Jhin,Galio,Ornn,Graves,Viktor,Kalista,Pantheon,Samira,Camille,Kayn,Kai'Sa,Miss Fortune,0
6449,Wukong,Nidalee,Sylas,Samira,Leona,Shen,Olaf,Ekko,Ashe,Pantheon,Sett,Renekton,Graves,Fiora,Volibear,0
6450,Shen,Kayn,LeBlanc,Samira,Rakan,Ornn,Hecarim,Akali,Jhin,Pantheon,Sett,Renekton,Graves,Alistar,Leona,0
6451,Jayce,Graves,Ekko,Ashe,Rakan,Renekton,Nidalee,Qiyana,Jhin,Pantheon,Olaf,Galio,Samira,Akali,Camille,0
6452,Shen,Lillia,Lucian,Jhin,Alistar,Volibear,Kayn,Akali,Vayne,Leona,Galio,Samira,Jayce,Sett,Twisted Fate,1

In [ ]:
The Champions in Cluster 3 are: ['Jayce' 'Quinn' 'Corki' 'Zoe' 'Vladimir' 'Syndra' 'Rumble' 'LeBlanc'
 "Vel'Koz" 'Viktor' 'Swain']
The Champions in Cluster 4 are: ['Thresh' 'Trundle' 'Skarner' 'Lulu' 'Jarvan IV' 'Taric' 'Leona'
 'Tahm Kench']

In [398]:
# df_banpick.to_csv("ban_pick_result.csv")

In [639]:
cluster

          cluster
champion
Karma           1
Nocturne       15
Lucian          6
Olaf           15
Fizz           15
...           ...
Shaco          20
Teemo          20
Warwick        20
Rammus         20
Annie          20

[147 rows x 1 columns]

In [640]:
bp_cluster_columns = [f"blu_pick_cluster{i}" for i in range(21)]
bp_cluster_columns.extend([f"red_pick_cluster{i}" for i in range(21)])
bp_cluster_columns.extend([f"ban_cluster{i}" for i in range(21)])
bp_cluster_columns.append('result')

In [456]:
bp_cluster_dict = {name:0 for name in bp_cluster_columns[:-1]}
df_bp_cluster = pd.DataFrame(columns = bp_cluster_columns,index = [0])
idx = 1
while idx <= 6452:
    try:
        for col in df_banpick.columns[:-1]:
            if ((col[:4]=='pick') and (int(col[4:])<=5)):
                try:            
                    bp_cluster_dict[f"blu_pick_cluster{cluster[cluster.index==df_banpick.loc[idx,col]].values[0][0]}"] +=1
                except:
                    pass            
            elif ((col[:4]=='pick') and (int(col[4:])>5)):
                try:
                    bp_cluster_dict[f"red_pick_cluster{cluster[cluster.index==df_banpick.loc[idx,col]].values[0][0]}"] +=1
                except:
                    pass            
            elif  col[:3]=='ban':
                try:
                    bp_cluster_dict[f"ban_cluster{cluster[cluster.index==df_banpick.loc[idx,col]].values[0][0]}"] +=1
                except:
                    pass
        bp_cluster_dict['result'] = df_banpick.loc[idx,'result']
        bp_cluster_df = pd.DataFrame(bp_cluster_dict,index=[idx])
        df_bp_cluster = df_bp_cluster.append(bp_cluster_df,ignore_index = True)
        idx+=1
        bp_cluster_dict = {name:0 for name in bp_cluster_columns[:-1]}
    except:
        print(cluster[cluster.index==df_banpick.loc[idx,col]].values[0][0])
        idx+=1
df_bp_cluster = df_bp_cluster.dropna()
df_bp_cluster = df_bp_cluster.astype(int)

In [606]:
df_bp_cluster.to_csv("df_bp_cluster20.csv")

In [648]:
df_bp_cluster = pd.read_csv("df_bp_cluster20.csv").set_index("Unnamed: 0")

In [678]:
total_cluster = 21
cluster_dict = {}
for i in range(0,total_cluster):
    for j in range(0,total_cluster):
        cluster_dict[f'b{i}r{j}']=[0,0]

for i in range(len(df_bp_cluster)):
    for b in range(0,total_cluster):
        for r in range(0,total_cluster):
            if (df_bp_cluster.loc[i+1,f'blu_pick_cluster{b}']>0) and (df_bp_cluster.loc[i+1,f'red_pick_cluster{r}'])>0:
                cluster_dict[f'b{b}r{r}'][0] += df_bp_cluster.loc[i+1,'result']
                cluster_dict[f'b{b}r{r}'][1] +=1
                
cluster_win_result = {}
for key, value in cluster_dict.items():
    if value[1] >=100: # delete result that has less than 10 games
        cluster_win_result[key] = value[0]/value[1]

In [679]:
        
cluster_win_result_blue = dict(sorted(cluster_win_result.items(), key=lambda item: item[1],reverse = True))
cluster_win_result_blue

{'b0r14': 0.6171875,
 'b19r0': 0.6075268817204301,
 'b2r0': 0.6066666666666667,
 'b15r14': 0.6024844720496895,
 'b7r8': 0.5996131528046421,
 'b1r5': 0.5987460815047022,
 'b15r8': 0.5857142857142857,
 'b3r5': 0.5824817518248175,
 'b17r0': 0.582010582010582,
 'b2r11': 0.5815295815295816,
 'b3r15': 0.579746835443038,
 'b7r15': 0.5792880258899676,
 'b7r0': 0.576271186440678,
 'b2r6': 0.5748987854251012,
 'b1r11': 0.5744400527009222,
 'b10r5': 0.5730593607305936,
 'b1r19': 0.5730088495575221,
 'b17r5': 0.5717255717255717,
 'b6r14': 0.570694087403599,
 'b11r5': 0.5704347826086956,
 'b3r8': 0.5703245749613601,
 'b15r18': 0.5696969696969697,
 'b7r11': 0.5690515806988353,
 'b2r2': 0.5689149560117303,
 'b3r18': 0.5683453237410072,
 'b4r5': 0.567741935483871,
 'b15r5': 0.5674603174603174,
 'b10r14': 0.5673758865248227,
 'b7r6': 0.5672937771345875,
 'b15r19': 0.5666666666666667,
 'b3r14': 0.5663157894736842,
 'b19r14': 0.5647382920110193,
 'b10r19': 0.5637860082304527,
 'b7r14': 0.5630252100840336,
 'b7r5': 0.562862669245648,
 'b7r1': 0.562390158172232,
 'b17r14': 0.5621468926553672,
 'b2r14': 0.5606694560669456,
 'b6r0': 0.56,
 'b18r5': 0.5594713656387665,
 'b7r19': 0.5593705293276109,
 'b4r8': 0.5593471810089021,
 'b14r18': 0.5591397849462365,
 'b3r11': 0.5588235294117647,
 'b0r5': 0.5574712643678161,
 'b7r4': 0.5571687840290381,
 'b10r18': 0.5568561872909699,
 'b8r11': 0.5559322033898305,
 'b5r8': 0.5558823529411765,
 'b7r17': 0.5555555555555556,
 'b18r11': 0.5555555555555556,
 'b3r0': 0.5551470588235294,
 'b3r19': 0.5547045951859956,
 'b11r14': 0.5533980582524272,
 'b2r5': 0.5527777777777778,
 'b0r19': 0.5527638190954773,
 'b3r3': 0.5526859504132231,
 'b19r19': 0.5524590163934426,
 'b7r18': 0.5521064301552107,
 'b10r0': 0.5516304347826086,
 'b8r14': 0.5515695067264574,
 'b15r11': 0.5509259259259259,
 'b19r8': 0.550321199143469,
 'b3r1': 0.5502793296089385,
 'b1r1': 0.5501930501930502,
 'b2r1': 0.5494791666666666,
 'b3r4': 0.5494584837545127,
 'b4r14': 0.548828125,
 'b17r4': 0.548768472906404,
 'b17r11': 0.5476190476190477,
 'b1r3': 0.5474683544303798,
 'b17r18': 0.5473372781065089,
 'b14r3': 0.5472527472527473,
 'b1r8': 0.5461741424802111,
 'b4r11': 0.5450674237047551,
 'b4r18': 0.5448979591836735,
 'b3r6': 0.5440251572327044,
 'b8r18': 0.543778801843318,
 'b10r8': 0.5436681222707423,
 'b19r5': 0.5432525951557093,
 'b7r3': 0.5428571428571428,
 'b1r10': 0.5427974947807933,
 'b10r11': 0.5425531914893617,
 'b5r1': 0.5425219941348973,
 'b17r6': 0.5425219941348973,
 'b2r4': 0.5423956931359354,
 'b8r15': 0.5421686746987951,
 'b4r19': 0.5421095666394112,
 'b18r10': 0.541958041958042,
 'b0r6': 0.5418326693227091,
 'b1r14': 0.5415282392026578,
 'b11r3': 0.5414301929625426,
 'b19r15': 0.541095890410959,
 'b1r4': 0.5410225921521997,
 'b1r0': 0.5408163265306123,
 'b2r3': 0.5408163265306123,
 'b2r8': 0.540785498489426,
 'b1r6': 0.5399673735725938,
 'b4r6': 0.5399610136452242,
 'b11r2': 0.538961038961039,
 'b4r15': 0.5382932166301969,
 'b2r17': 0.5365853658536586,
 'b3r10': 0.5365013774104683,
 'b8r17': 0.5364583333333334,
 'b11r19': 0.5360094451003542,
 'b17r19': 0.5357142857142857,
 'b10r4': 0.5353099730458221,
 'b3r2': 0.5341880341880342,
 'b18r4': 0.5341130604288499,
 'b10r2': 0.5340659340659341,
 'b4r3': 0.533988533988534,
 'b17r10': 0.5339805825242718,
 'b19r18': 0.5337423312883436,
 'b2r19': 0.533066132264529,
 'b17r2': 0.5329087048832272,
 'b10r6': 0.5324259407526021,
 'b4r0': 0.5323076923076923,
 'b19r4': 0.5321955003878976,
 'b2r10': 0.532043530834341,
 'b0r11': 0.53156146179402,
 'b19r10': 0.5313304721030043,
 'b7r2': 0.5313092979127134,
 'b11r0': 0.5306859205776173,
 'b7r7': 0.5305343511450382,
 'b1r7': 0.530373831775701,
 'b10r3': 0.5303354746609564,
 'b1r17': 0.5298372513562387,
 'b4r2': 0.5297157622739018,
 'b7r10': 0.5293103448275862,
 'b11r18': 0.529126213592233,
 'b2r15': 0.5288461538461539,
 'b4r4': 0.5283714075165807,
 'b6r4': 0.5283582089552239,
 'b8r5': 0.528125,
 'b19r3': 0.5267349260523322,
 'b10r15': 0.5265151515151515,
 'b18r3': 0.5264423076923077,
 'b17r3': 0.5263819095477387,
 'b19r11': 0.525918944392083,
 'b11r11': 0.5255041518386714,
 'b5r11': 0.5252679938744257,
 'b11r4': 0.5251857968620974,
 'b10r10': 0.525027808676307,
 'b6r2': 0.5247524752475248,
 'b6r19': 0.5245664739884393,
 'b0r4': 0.5238095238095238,
 'b5r14': 0.5236220472440944,
 'b15r6': 0.523121387283237,
 'b1r15': 0.5230125523012552,
 'b5r5': 0.5229357798165137,
 'b8r8': 0.5228215767634855,
 'b17r15': 0.5209790209790209,
 'b5r6': 0.520746887966805,
 'b14r15': 0.5207100591715976,
 'b4r1': 0.520671834625323,
 'b17r8': 0.5205183585313174,
 'b6r5': 0.5203426124197003,
 'b8r4': 0.5198237885462555,
 'b18r19': 0.5197568389057751,
 'b14r5': 0.5190476190476191,
 'b14r1': 0.5187713310580204,
 'b0r8': 0.5185185185185185,
 'b2r18': 0.5183673469387755,
 'b9r10': 0.5179856115107914,
 'b6r18': 0.5179153094462541,
 'b17r17': 0.5177935943060499,
 'b4r17': 0.5177777777777778,
 'b18r15': 0.5161290322580645,
 'b10r1': 0.5160965794768612,
 'b15r4': 0.515748031496063,
 'b3r17': 0.5154130702836005,
 'b19r7': 0.515358361774744,
 'b8r19': 0.5150812064965197,
 'b6r11': 0.514721919302072,
 'b15r17': 0.5143884892086331,
 'b5r19': 0.5135135135135135,
 'b14r19': 0.5134408602150538,
 'b19r6': 0.5129958960328317,
 'b9r11': 0.5128205128205128,
 'b8r6': 0.5118790496760259,
 'b8r10': 0.5115646258503401,
 'b17r7': 0.5114503816793893,
 'b14r0': 0.5112781954887218,
 'b3r7': 0.5112285336856011,
 'b15r10': 0.510989010989011,
 'b8r3': 0.5103969754253308,
 'b19r2': 0.5102420856610801,
 'b6r1': 0.5102040816326531,
 'b18r14': 0.51010101010101,
 'b1r18': 0.51,
 'b3r9': 0.5098039215686274,
 'b0r10': 0.5095890410958904,
 'b10r17': 0.5090415913200723,
 'b18r8': 0.5089285714285714,
 'b11r8': 0.5087719298245614,
 'b18r1': 0.5085324232081911,
 'b19r1': 0.5078299776286354,
 'b18r6': 0.5075528700906344,
 'b14r8': 0.5073170731707317,
 'b5r4': 0.5063613231552163,
 'b4r10': 0.5062344139650873,
 'b5r3': 0.5061511423550088,
 'b15r1': 0.5059760956175299,
 'b6r6': 0.5058430717863105,
 'b14r17': 0.505464480874317,
 'b11r10': 0.5052377115229654,
 'b15r0': 0.5047619047619047,
 'b6r3': 0.5043156596794082,
 'b11r6': 0.5041716328963052,
 'b10r7': 0.5039840637450199,
 'b5r0': 0.5033557046979866,
 'b18r17': 0.5031446540880503,
 'b8r2': 0.5028409090909091,
 'b6r10': 0.5023923444976076,
 'b6r8': 0.5012224938875306,
 'b14r10': 0.5,
 'b17r1': 0.5,
 'b19r17': 0.5,
 'b15r3': 0.49876543209876545,
 'b18r7': 0.49865951742627346,
 'b6r15': 0.49836065573770494,
 'b14r7': 0.49829351535836175,
 'b11r7': 0.49754901960784315,
 'b11r15': 0.49702380952380953,
 'b10r9': 0.4965986394557823,
 'b11r1': 0.49568221070811747,
 'b5r15': 0.49523809523809526,
 'b14r4': 0.49454545454545457,
 'b1r2': 0.4918793503480278,
 'b14r11': 0.49166666666666664,
 'b6r17': 0.4906937394247039,
 'b4r7': 0.4905897114178168,
 'b15r2': 0.4898785425101215,
 'b5r18': 0.4895397489539749,
 'b0r18': 0.488,
 'b2r7': 0.48663101604278075,
 'b6r7': 0.48659003831417624,
 'b0r7': 0.4863636363636364,
 'b8r1': 0.48633879781420764,
 'b15r7': 0.48507462686567165,
 'b14r2': 0.48412698412698413,
 'b0r2': 0.483695652173913,
 'b0r17': 0.4830917874396135,
 'b0r3': 0.4828897338403042,
 'b5r10': 0.48174157303370785,
 'b5r2': 0.4810126582278481,
 'b11r17': 0.4809590973201692,
 'b9r3': 0.4807692307692308,
 'b14r6': 0.47783251231527096,
 'b4r9': 0.47619047619047616,
 'b5r7': 0.47480106100795755,
 'b18r2': 0.4713114754098361,
 'b9r4': 0.46853146853146854,
 'b0r1': 0.46703296703296704,
 'b5r17': 0.46701846965699206,
 'b8r0': 0.45454545454545453,
 'b8r7': 0.4543147208121827,
 'b9r6': 0.4396551724137931,
 'b14r14': 0.4316546762589928}

In [680]:
        
cluster_win_result_red = dict(sorted(cluster_win_result.items(), key=lambda item: item[1],reverse = False))
for key,value in cluster_win_result_red.items():
    cluster_win_result_red[key] = 1-value
cluster_win_result_red

{'b14r14': 0.5683453237410072,
 'b9r6': 0.5603448275862069,
 'b8r7': 0.5456852791878173,
 'b8r0': 0.5454545454545454,
 'b5r17': 0.5329815303430079,
 'b0r1': 0.532967032967033,
 'b9r4': 0.5314685314685315,
 'b18r2': 0.5286885245901639,
 'b5r7': 0.5251989389920424,
 'b4r9': 0.5238095238095238,
 'b14r6': 0.5221674876847291,
 'b9r3': 0.5192307692307692,
 'b11r17': 0.5190409026798308,
 'b5r2': 0.5189873417721519,
 'b5r10': 0.5182584269662922,
 'b0r3': 0.5171102661596958,
 'b0r17': 0.5169082125603865,
 'b0r2': 0.5163043478260869,
 'b14r2': 0.5158730158730158,
 'b15r7': 0.5149253731343284,
 'b8r1': 0.5136612021857924,
 'b0r7': 0.5136363636363637,
 'b6r7': 0.5134099616858238,
 'b2r7': 0.5133689839572193,
 'b0r18': 0.512,
 'b5r18': 0.5104602510460251,
 'b15r2': 0.5101214574898785,
 'b4r7': 0.5094102885821832,
 'b6r17': 0.509306260575296,
 'b14r11': 0.5083333333333333,
 'b1r2': 0.5081206496519721,
 'b14r4': 0.5054545454545454,
 'b5r15': 0.5047619047619047,
 'b11r1': 0.5043177892918825,
 'b10r9': 0.5034013605442177,
 'b11r15': 0.5029761904761905,
 'b11r7': 0.5024509803921569,
 'b14r7': 0.5017064846416383,
 'b6r15': 0.5016393442622951,
 'b18r7': 0.5013404825737265,
 'b15r3': 0.5012345679012346,
 'b14r10': 0.5,
 'b17r1': 0.5,
 'b19r17': 0.5,
 'b6r8': 0.4987775061124694,
 'b6r10': 0.4976076555023924,
 'b8r2': 0.49715909090909094,
 'b18r17': 0.4968553459119497,
 'b5r0': 0.49664429530201337,
 'b10r7': 0.4960159362549801,
 'b11r6': 0.4958283671036948,
 'b6r3': 0.49568434032059183,
 'b15r0': 0.49523809523809526,
 'b11r10': 0.49476228847703463,
 'b14r17': 0.49453551912568305,
 'b6r6': 0.4941569282136895,
 'b15r1': 0.4940239043824701,
 'b5r3': 0.4938488576449912,
 'b4r10': 0.4937655860349127,
 'b5r4': 0.4936386768447837,
 'b14r8': 0.4926829268292683,
 'b18r6': 0.49244712990936557,
 'b19r1': 0.49217002237136465,
 'b18r1': 0.49146757679180886,
 'b11r8': 0.49122807017543857,
 'b18r8': 0.4910714285714286,
 'b10r17': 0.4909584086799277,
 'b0r10': 0.4904109589041096,
 'b3r9': 0.4901960784313726,
 'b1r18': 0.49,
 'b18r14': 0.48989898989898994,
 'b6r1': 0.4897959183673469,
 'b19r2': 0.4897579143389199,
 'b8r3': 0.4896030245746692,
 'b15r10': 0.48901098901098905,
 'b3r7': 0.48877146631439894,
 'b14r0': 0.4887218045112782,
 'b17r7': 0.4885496183206107,
 'b8r10': 0.4884353741496599,
 'b8r6': 0.48812095032397407,
 'b9r11': 0.4871794871794872,
 'b19r6': 0.4870041039671683,
 'b14r19': 0.48655913978494625,
 'b5r19': 0.4864864864864865,
 'b15r17': 0.4856115107913669,
 'b6r11': 0.485278080697928,
 'b8r19': 0.4849187935034803,
 'b19r7': 0.48464163822525597,
 'b3r17': 0.4845869297163995,
 'b15r4': 0.48425196850393704,
 'b10r1': 0.48390342052313884,
 'b18r15': 0.4838709677419355,
 'b4r17': 0.4822222222222222,
 'b17r17': 0.4822064056939501,
 'b6r18': 0.4820846905537459,
 'b9r10': 0.48201438848920863,
 'b2r18': 0.4816326530612245,
 'b0r8': 0.4814814814814815,
 'b14r1': 0.4812286689419796,
 'b14r5': 0.4809523809523809,
 'b18r19': 0.48024316109422494,
 'b8r4': 0.48017621145374445,
 'b6r5': 0.47965738758029974,
 'b17r8': 0.47948164146868255,
 'b4r1': 0.47932816537467704,
 'b14r15': 0.47928994082840237,
 'b5r6': 0.479253112033195,
 'b17r15': 0.47902097902097907,
 'b8r8': 0.4771784232365145,
 'b5r5': 0.47706422018348627,
 'b1r15': 0.4769874476987448,
 'b15r6': 0.476878612716763,
 'b5r14': 0.47637795275590555,
 'b0r4': 0.47619047619047616,
 'b6r19': 0.47543352601156075,
 'b6r2': 0.4752475247524752,
 'b10r10': 0.47497219132369295,
 'b11r4': 0.47481420313790257,
 'b5r11': 0.4747320061255743,
 'b11r11': 0.4744958481613286,
 'b19r11': 0.474081055607917,
 'b17r3': 0.47361809045226133,
 'b18r3': 0.4735576923076923,
 'b10r15': 0.4734848484848485,
 'b19r3': 0.4732650739476678,
 'b8r5': 0.47187500000000004,
 'b6r4': 0.4716417910447761,
 'b4r4': 0.47162859248341926,
 'b2r15': 0.47115384615384615,
 'b11r18': 0.470873786407767,
 'b7r10': 0.4706896551724138,
 'b4r2': 0.4702842377260982,
 'b1r17': 0.4701627486437613,
 'b10r3': 0.46966452533904357,
 'b1r7': 0.46962616822429903,
 'b7r7': 0.4694656488549618,
 'b11r0': 0.4693140794223827,
 'b7r2': 0.4686907020872866,
 'b19r10': 0.4686695278969957,
 'b0r11': 0.46843853820598,
 'b2r10': 0.46795646916565903,
 'b19r4': 0.46780449961210235,
 'b4r0': 0.46769230769230774,
 'b10r6': 0.4675740592473979,
 'b17r2': 0.46709129511677283,
 'b2r19': 0.46693386773547096,
 'b19r18': 0.4662576687116564,
 'b17r10': 0.46601941747572817,
 'b4r3': 0.46601146601146604,
 'b10r2': 0.46593406593406594,
 'b18r4': 0.4658869395711501,
 'b3r2': 0.4658119658119658,
 'b10r4': 0.46469002695417794,
 'b17r19': 0.4642857142857143,
 'b11r19': 0.4639905548996458,
 'b8r17': 0.46354166666666663,
 'b3r10': 0.4634986225895317,
 'b2r17': 0.46341463414634143,
 'b4r15': 0.4617067833698031,
 'b11r2': 0.461038961038961,
 'b4r6': 0.4600389863547758,
 'b1r6': 0.46003262642740617,
 'b2r8': 0.45921450151057397,
 'b1r0': 0.4591836734693877,
 'b2r3': 0.4591836734693877,
 'b1r4': 0.4589774078478003,
 'b19r15': 0.45890410958904104,
 'b11r3': 0.4585698070374574,
 'b1r14': 0.4584717607973422,
 'b0r6': 0.4581673306772909,
 'b18r10': 0.458041958041958,
 'b4r19': 0.45789043336058877,
 'b8r15': 0.45783132530120485,
 'b2r4': 0.4576043068640646,
 'b5r1': 0.4574780058651027,
 'b17r6': 0.4574780058651027,
 'b10r11': 0.45744680851063835,
 'b1r10': 0.4572025052192067,
 'b7r3': 0.4571428571428572,
 'b19r5': 0.45674740484429066,
 'b10r8': 0.45633187772925765,
 'b8r18': 0.45622119815668205,
 'b3r6': 0.4559748427672956,
 'b4r18': 0.45510204081632655,
 'b4r11': 0.45493257629524486,
 'b1r8': 0.4538258575197889,
 'b14r3': 0.4527472527472527,
 'b17r18': 0.4526627218934911,
 'b1r3': 0.4525316455696202,
 'b17r11': 0.45238095238095233,
 'b17r4': 0.45123152709359604,
 'b4r14': 0.451171875,
 'b3r4': 0.45054151624548733,
 'b2r1': 0.45052083333333337,
 'b1r1': 0.4498069498069498,
 'b3r1': 0.44972067039106145,
 'b19r8': 0.449678800856531,
 'b15r11': 0.44907407407407407,
 'b8r14': 0.44843049327354256,
 'b10r0': 0.44836956521739135,
 'b7r18': 0.44789356984478934,
 'b19r19': 0.44754098360655736,
 'b3r3': 0.4473140495867769,
 'b0r19': 0.44723618090452266,
 'b2r5': 0.4472222222222222,
 'b11r14': 0.44660194174757284,
 'b3r19': 0.4452954048140044,
 'b3r0': 0.44485294117647056,
 'b7r17': 0.4444444444444444,
 'b18r11': 0.4444444444444444,
 'b5r8': 0.4441176470588235,
 'b8r11': 0.4440677966101695,
 'b10r18': 0.44314381270903014,
 'b7r4': 0.44283121597096187,
 'b0r5': 0.44252873563218387,
 'b3r11': 0.4411764705882353,
 'b14r18': 0.4408602150537635,
 'b4r8': 0.44065281899109787,
 'b7r19': 0.4406294706723891,
 'b18r5': 0.44052863436123346,
 'b6r0': 0.43999999999999995,
 'b2r14': 0.4393305439330544,
 'b17r14': 0.4378531073446328,
 'b7r1': 0.43760984182776796,
 'b7r5': 0.437137330754352,
 'b7r14': 0.4369747899159664,
 'b10r19': 0.43621399176954734,
 'b19r14': 0.4352617079889807,
 'b3r14': 0.4336842105263158,
 'b15r19': 0.43333333333333335,
 'b7r6': 0.4327062228654125,
 'b10r14': 0.43262411347517726,
 'b15r5': 0.43253968253968256,
 'b4r5': 0.432258064516129,
 'b3r18': 0.4316546762589928,
 'b2r2': 0.43108504398826974,
 'b7r11': 0.4309484193011647,
 'b15r18': 0.4303030303030303,
 'b3r8': 0.42967542503863987,
 'b11r5': 0.4295652173913044,
 'b6r14': 0.42930591259640105,
 'b17r5': 0.4282744282744283,
 'b1r19': 0.42699115044247793,
 'b10r5': 0.4269406392694064,
 'b1r11': 0.42555994729907776,
 'b2r6': 0.4251012145748988,
 'b7r0': 0.423728813559322,
 'b7r15': 0.42071197411003236,
 'b3r15': 0.42025316455696204,
 'b2r11': 0.41847041847041844,
 'b17r0': 0.417989417989418,
 'b3r5': 0.41751824817518246,
 'b15r8': 0.41428571428571426,
 'b1r5': 0.4012539184952978,
 'b7r8': 0.4003868471953579,
 'b15r14': 0.39751552795031053,
 'b2r0': 0.3933333333333333,
 'b19r0': 0.3924731182795699,
 'b0r14': 0.3828125}

In [682]:
for i in range(21):
    print(f"The Champions in Cluster {i} are:", cluster[cluster['cluster']==i].index.values)

The Champions in Cluster 0 are: ['Senna' 'Twitch' 'Jinx' 'Taliyah' 'Vayne']
The Champions in Cluster 1 are: ['Karma' 'Lux' 'Nunu & Willump' 'Volibear' 'Xin Zhao' 'Bard' 'Blitzcrank'
 'Morgana' 'Soraka']
The Champions in Cluster 2 are: ['Fiora' 'Irelia' 'Twisted Fate' 'Jax' 'Riven' 'Tristana' 'Tryndamere'
 'Camille' 'Aatrox']
The Champions in Cluster 3 are: ['Jayce' 'Quinn' 'Corki' 'Zoe' 'Vladimir' 'Syndra' 'Rumble' 'LeBlanc'
 "Vel'Koz" 'Viktor' 'Swain']
The Champions in Cluster 4 are: ['Thresh' 'Trundle' 'Skarner' 'Lulu' 'Jarvan IV' 'Taric' 'Leona'
 'Tahm Kench']
The Champions in Cluster 5 are: ['Sejuani' 'Pyke' 'Lee Sin' "Rek'Sai"]
The Champions in Cluster 6 are: ['Lucian' 'Dr. Mundo' 'Talon' 'Akali' 'Ekko' 'Aurelion Sol' 'Diana'
 'Yorick' 'Cassiopeia' 'Sylas' 'Ahri' 'Ryze' 'Qiyana' 'Orianna' "Cho'Gath"]
The Champions in Cluster 7 are: ['Sivir' 'Varus' 'Caitlyn' 'Aphelios']
The Champions in Cluster 8 are: ['Malphite' 'Mordekaiser' 'Gnar' 'Neeko' 'Yuumi' 'Singed' 'Lissandra'
 'Fiddlesticks' 'Zilean' 'Kennen' 'Maokai' 'Malzahar']
The Champions in Cluster 9 are: ['Zyra' 'Karthus' 'Xerath' 'Heimerdinger' 'Ziggs' 'Illaoi']
The Champions in Cluster 10 are: ['Sion' 'Urgot' 'Kled' 'Shen' 'Ornn' 'Renekton' 'Galio' 'Poppy' 'Wukong'
 'Darius' 'Sett']
The Champions in Cluster 11 are: ['Draven' 'Miss Fortune' 'Ashe' 'Jhin' "Kai'Sa" 'Kalista' 'Xayah']
The Champions in Cluster 12 are: ['Janna' 'Vi' 'Anivia' 'Sona']
The Champions in Cluster 13 are: ['Garen']
The Champions in Cluster 14 are: ['Gangplank' 'Evelynn' 'Azir' 'Lillia' 'Zed' 'Kayle']
The Champions in Cluster 15 are: ['Nocturne' 'Olaf' 'Fizz' 'Zac' 'Yasuo' 'Hecarim' 'Pantheon']
The Champions in Cluster 16 are: ['Veigar' 'Kassadin']
The Champions in Cluster 17 are: ["Kha'Zix" 'Graves' 'Nidalee' 'Gragas' 'Kayn' 'Elise' 'Kindred']
The Champions in Cluster 18 are: ["Kog'Maw" 'Shyvana' 'Ezreal']
The Champions in Cluster 19 are: ['Alistar' 'Rakan' 'Ivern' 'Braum' 'Nami' 'Nautilus']
The Champions in Cluster 20 are: ['Master Yi' 'Rengar' 'Amumu' 'Brand' 'Katarina' 'Shaco' 'Teemo' 'Warwick'
 'Rammus' 'Annie']

## 10 Cluster

In [628]:
cluster10 = pd.read_csv("cluster_winloss10.csv").set_index('champion').drop(columns = "Unnamed: 0")
for i in range(11):
    print(f"The Champions in Cluster {i} are:", cluster10[cluster10['cluster']==i].index.values)

The Champions in Cluster 0 are: ['Jax' 'Graves' 'Kindred' 'Ekko' 'Tristana' 'Elise' 'Kalista' 'Camille'
 'Fiora' 'Tryndamere' 'Hecarim' 'Irelia' 'Riven' 'Gragas' 'Nidalee'
 "Kha'Zix"]
The Champions in Cluster 1 are: ['Sejuani' 'Pyke' 'Yasuo' 'Volibear' "Rek'Sai" 'Lee Sin' 'Olaf' 'Sona'
 'Anivia' 'Vi' 'Zac' 'Nocturne']
The Champions in Cluster 2 are: ['Ziggs' "Kog'Maw" 'Shyvana' 'Xerath' 'Ezreal' 'Heimerdinger' 'Illaoi'
 'Zyra' 'Karthus']
The Champions in Cluster 3 are: ['Trundle' 'Skarner' 'Leona' 'Ivern' 'Taric' 'Nami' 'Lulu' 'Jarvan IV'
 'Nautilus' 'Tahm Kench' 'Alistar' 'Thresh' 'Braum' 'Rakan']
The Champions in Cluster 4 are: ['Urgot' 'Poppy' 'Twisted Fate' 'Kled' 'Ornn' 'Sett' 'Renekton' 'Shen'
 'Darius' 'Sion' 'Galio' 'Zilean' 'Wukong' 'Pantheon' 'Fiddlesticks'
 'Aatrox' 'Malphite' 'Singed']
The Champions in Cluster 5 are: ["Cho'Gath" 'Veigar' 'Kayn' 'Fizz' 'Diana' 'Ahri' 'Cassiopeia' 'Talon'
 'Akali' 'Aurelion Sol' 'Yorick' 'Ryze' 'Yuumi' 'Kassadin' 'Qiyana'
 'Sylas']
The Champions in Cluster 6 are: ['Azir' 'Orianna' 'Evelynn' 'Maokai' 'Dr. Mundo' 'Neeko' 'Mordekaiser'
 'Zed' 'Malzahar' 'Lucian' 'Kayle' 'Gnar' 'Kennen' 'Lissandra']
The Champions in Cluster 7 are: ['Bard' 'Lux' 'Nunu & Willump' 'Xin Zhao' 'Garen' 'Morgana' 'Blitzcrank'
 'Karma' 'Janna' 'Soraka']
The Champions in Cluster 8 are: ['Jayce' 'Rumble' 'Swain' 'Viktor' 'Quinn' 'Corki' 'LeBlanc' "Vel'Koz"
 'Lillia' 'Taliyah' 'Gangplank' 'Zoe' 'Syndra' 'Vladimir' 'Senna']
The Champions in Cluster 9 are: ['Vayne' 'Draven' 'Caitlyn' 'Jinx' 'Jhin' 'Sivir' 'Aphelios'
 'Miss Fortune' "Kai'Sa" 'Ashe' 'Twitch' 'Xayah' 'Varus']
The Champions in Cluster 10 are: ['Teemo' 'Brand' 'Rengar' 'Rammus' 'Master Yi' 'Shaco' 'Warwick' 'Annie'
 'Amumu' 'Katarina']

In [629]:
total_cluster = 11
bp_cluster_columns = [f"blu_pick_cluster{i}" for i in range(total_cluster)]
bp_cluster_columns.extend([f"red_pick_cluster{i}" for i in range(total_cluster)])
bp_cluster_columns.extend([f"ban_cluster{i}" for i in range(total_cluster)])
bp_cluster_columns.append('result')

In [631]:
df_banpick

,pick1,pick2,pick3,pick4,pick5,pick6,pick7,pick8,pick9,pick10,ban1,ban2,ban3,ban4,ban5,result
Unnamed: 0,,,,,,,,,,,,,,,,
1,Rumble,Elise,Qiyana,Miss Fortune,Nautilus,Aatrox,Gragas,Mordekaiser,Xayah,Rakan,Lucian,Akali,Lee Sin,Olaf,Jarvan IV,1
2,Jayce,Jarvan IV,Orianna,Miss Fortune,Nautilus,Aatrox,Elise,Qiyana,Varus,Tahm Kench,Lucian,Akali,Rek'Sai,Irelia,Camille,0
3,Renekton,Rek'Sai,Mordekaiser,Xayah,Rakan,Aatrox,Sejuani,Azir,Miss Fortune,Nautilus,Lucian,Akali,Elise,Irelia,Orianna,1
4,Pantheon,Elise,Nautilus,Xayah,Rakan,Quinn,Olaf,Orianna,Miss Fortune,Leona,Lucian,Rek'Sai,Akali,Renekton,Qiyana,0
5,Mordekaiser,Jarvan IV,Ryze,Xayah,Rakan,Renekton,Elise,Vel'Koz,Varus,Braum,Miss Fortune,Akali,Lucian,Lee Sin,Rumble,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6448,Akali,Hecarim,Irelia,Jhin,Galio,Ornn,Graves,Viktor,Kalista,Pantheon,Samira,Camille,Kayn,Kai'Sa,Miss Fortune,0
6449,Wukong,Nidalee,Sylas,Samira,Leona,Shen,Olaf,Ekko,Ashe,Pantheon,Sett,Renekton,Graves,Fiora,Volibear,0
6450,Shen,Kayn,LeBlanc,Samira,Rakan,Ornn,Hecarim,Akali,Jhin,Pantheon,Sett,Renekton,Graves,Alistar,Leona,0
6451,Jayce,Graves,Ekko,Ashe,Rakan,Renekton,Nidalee,Qiyana,Jhin,Pantheon,Olaf,Galio,Samira,Akali,Camille,0
6452,Shen,Lillia,Lucian,Jhin,Alistar,Volibear,Kayn,Akali,Vayne,Leona,Galio,Samira,Jayce,Sett,Twisted Fate,1

In [632]:
bp_cluster_dict = {name:0 for name in bp_cluster_columns[:-1]}
df_bp_cluster = pd.DataFrame(columns = bp_cluster_columns,index = [0])
idx = 1
while idx <= 6452:
    try:
        for col in df_banpick.columns[:-1]:
            if ((col[:4]=='pick') and (int(col[4:])<=5)):
                try:            
                    bp_cluster_dict[f"blu_pick_cluster{cluster[cluster.index==df_banpick.loc[idx,col]].values[0][0]}"] +=1
                except:
                    pass            
            elif ((col[:4]=='pick') and (int(col[4:])>5)):
                try:
                    bp_cluster_dict[f"red_pick_cluster{cluster[cluster.index==df_banpick.loc[idx,col]].values[0][0]}"] +=1
                except:
                    pass            
            elif  col[:3]=='ban':
                try:
                    bp_cluster_dict[f"ban_cluster{cluster[cluster.index==df_banpick.loc[idx,col]].values[0][0]}"] +=1
                except:
                    pass
        bp_cluster_dict['result'] = df_banpick.loc[idx,'result']
        bp_cluster_df = pd.DataFrame(bp_cluster_dict,index=[idx])
        df_bp_cluster = df_bp_cluster.append(bp_cluster_df,ignore_index = True)
        idx+=1
        bp_cluster_dict = {name:0 for name in bp_cluster_columns[:-1]}
    except:
        print(cluster[cluster.index==df_banpick.loc[idx,col]].values[0][0])
        idx+=1

In [683]:
df_bp_cluster = df_bp_cluster.dropna()
df_bp_cluster = df_bp_cluster.astype(int)
df_bp_cluster.to_csv("df_bp_cluster10.csv")

df_bp_cluster = pd.read_csv("df_bp_cluster10.csv").set_index("Unnamed: 0")

In [684]:
total_cluster = 11
cluster_dict = {}
for i in range(0,total_cluster):
    for j in range(0,total_cluster):
        cluster_dict[f'b{i}r{j}']=[0,0]

for i in range(len(df_bp_cluster)):
    for b in range(0,total_cluster):
        for r in range(0,total_cluster):
            if (df_bp_cluster.loc[i+1,f'blu_pick_cluster{b}']>0) and (df_bp_cluster.loc[i+1,f'red_pick_cluster{r}'])>0:
                cluster_dict[f'b{b}r{r}'][0] += df_bp_cluster.loc[i+1,'result']
                cluster_dict[f'b{b}r{r}'][1] +=1
                
cluster_win_result = {}
for key, value in cluster_dict.items():
    if value[1] >=100: # delete result that has less than 10 games
        cluster_win_result[key] = value[0]/value[1]
        
cluster_win_result = dict(sorted(cluster_win_result.items(), key=lambda item: item[1],reverse = True))
cluster_win_result

{'b2r0': 0.6066666666666667,
 'b7r8': 0.5996131528046421,
 'b1r5': 0.5987460815047022,
 'b3r5': 0.5824817518248175,
 'b7r0': 0.576271186440678,
 'b2r6': 0.5748987854251012,
 'b10r5': 0.5730593607305936,
 'b3r8': 0.5703245749613601,
 'b2r2': 0.5689149560117303,
 'b4r5': 0.567741935483871,
 'b7r6': 0.5672937771345875,
 'b7r5': 0.562862669245648,
 'b7r1': 0.562390158172232,
 'b6r0': 0.56,
 'b4r8': 0.5593471810089021,
 'b0r5': 0.5574712643678161,
 'b7r4': 0.5571687840290381,
 'b5r8': 0.5558823529411765,
 'b3r0': 0.5551470588235294,
 'b2r5': 0.5527777777777778,
 'b3r3': 0.5526859504132231,
 'b10r0': 0.5516304347826086,
 'b3r1': 0.5502793296089385,
 'b1r1': 0.5501930501930502,
 'b2r1': 0.5494791666666666,
 'b3r4': 0.5494584837545127,
 'b1r3': 0.5474683544303798,
 'b1r8': 0.5461741424802111,
 'b3r6': 0.5440251572327044,
 'b10r8': 0.5436681222707423,
 'b7r3': 0.5428571428571428,
 'b1r10': 0.5427974947807933,
 'b5r1': 0.5425219941348973,
 'b2r4': 0.5423956931359354,
 'b0r6': 0.5418326693227091,
 'b1r4': 0.5410225921521997,
 'b1r0': 0.5408163265306123,
 'b2r3': 0.5408163265306123,
 'b2r8': 0.540785498489426,
 'b1r6': 0.5399673735725938,
 'b4r6': 0.5399610136452242,
 'b3r10': 0.5365013774104683,
 'b10r4': 0.5353099730458221,
 'b3r2': 0.5341880341880342,
 'b10r2': 0.5340659340659341,
 'b4r3': 0.533988533988534,
 'b10r6': 0.5324259407526021,
 'b4r0': 0.5323076923076923,
 'b2r10': 0.532043530834341,
 'b7r2': 0.5313092979127134,
 'b7r7': 0.5305343511450382,
 'b1r7': 0.530373831775701,
 'b10r3': 0.5303354746609564,
 'b4r2': 0.5297157622739018,
 'b7r10': 0.5293103448275862,
 'b4r4': 0.5283714075165807,
 'b6r4': 0.5283582089552239,
 'b8r5': 0.528125,
 'b10r10': 0.525027808676307,
 'b6r2': 0.5247524752475248,
 'b0r4': 0.5238095238095238,
 'b5r5': 0.5229357798165137,
 'b8r8': 0.5228215767634855,
 'b5r6': 0.520746887966805,
 'b4r1': 0.520671834625323,
 'b6r5': 0.5203426124197003,
 'b8r4': 0.5198237885462555,
 'b0r8': 0.5185185185185185,
 'b9r10': 0.5179856115107914,
 'b10r1': 0.5160965794768612,
 'b8r6': 0.5118790496760259,
 'b8r10': 0.5115646258503401,
 'b3r7': 0.5112285336856011,
 'b8r3': 0.5103969754253308,
 'b6r1': 0.5102040816326531,
 'b3r9': 0.5098039215686274,
 'b0r10': 0.5095890410958904,
 'b5r4': 0.5063613231552163,
 'b4r10': 0.5062344139650873,
 'b5r3': 0.5061511423550088,
 'b6r6': 0.5058430717863105,
 'b6r3': 0.5043156596794082,
 'b10r7': 0.5039840637450199,
 'b5r0': 0.5033557046979866,
 'b8r2': 0.5028409090909091,
 'b6r10': 0.5023923444976076,
 'b6r8': 0.5012224938875306,
 'b10r9': 0.4965986394557823,
 'b1r2': 0.4918793503480278,
 'b4r7': 0.4905897114178168,
 'b2r7': 0.48663101604278075,
 'b6r7': 0.48659003831417624,
 'b0r7': 0.4863636363636364,
 'b8r1': 0.48633879781420764,
 'b0r2': 0.483695652173913,
 'b0r3': 0.4828897338403042,
 'b5r10': 0.48174157303370785,
 'b5r2': 0.4810126582278481,
 'b9r3': 0.4807692307692308,
 'b4r9': 0.47619047619047616,
 'b5r7': 0.47480106100795755,
 'b9r4': 0.46853146853146854,
 'b0r1': 0.46703296703296704,
 'b8r0': 0.45454545454545453,
 'b8r7': 0.4543147208121827,
 'b9r6': 0.4396551724137931}

In [685]:
        
cluster_win_result_blue = dict(sorted(cluster_win_result.items(), key=lambda item: item[1],reverse = True))
cluster_win_result_blue

{'b2r0': 0.6066666666666667,
 'b7r8': 0.5996131528046421,
 'b1r5': 0.5987460815047022,
 'b3r5': 0.5824817518248175,
 'b7r0': 0.576271186440678,
 'b2r6': 0.5748987854251012,
 'b10r5': 0.5730593607305936,
 'b3r8': 0.5703245749613601,
 'b2r2': 0.5689149560117303,
 'b4r5': 0.567741935483871,
 'b7r6': 0.5672937771345875,
 'b7r5': 0.562862669245648,
 'b7r1': 0.562390158172232,
 'b6r0': 0.56,
 'b4r8': 0.5593471810089021,
 'b0r5': 0.5574712643678161,
 'b7r4': 0.5571687840290381,
 'b5r8': 0.5558823529411765,
 'b3r0': 0.5551470588235294,
 'b2r5': 0.5527777777777778,
 'b3r3': 0.5526859504132231,
 'b10r0': 0.5516304347826086,
 'b3r1': 0.5502793296089385,
 'b1r1': 0.5501930501930502,
 'b2r1': 0.5494791666666666,
 'b3r4': 0.5494584837545127,
 'b1r3': 0.5474683544303798,
 'b1r8': 0.5461741424802111,
 'b3r6': 0.5440251572327044,
 'b10r8': 0.5436681222707423,
 'b7r3': 0.5428571428571428,
 'b1r10': 0.5427974947807933,
 'b5r1': 0.5425219941348973,
 'b2r4': 0.5423956931359354,
 'b0r6': 0.5418326693227091,
 'b1r4': 0.5410225921521997,
 'b1r0': 0.5408163265306123,
 'b2r3': 0.5408163265306123,
 'b2r8': 0.540785498489426,
 'b1r6': 0.5399673735725938,
 'b4r6': 0.5399610136452242,
 'b3r10': 0.5365013774104683,
 'b10r4': 0.5353099730458221,
 'b3r2': 0.5341880341880342,
 'b10r2': 0.5340659340659341,
 'b4r3': 0.533988533988534,
 'b10r6': 0.5324259407526021,
 'b4r0': 0.5323076923076923,
 'b2r10': 0.532043530834341,
 'b7r2': 0.5313092979127134,
 'b7r7': 0.5305343511450382,
 'b1r7': 0.530373831775701,
 'b10r3': 0.5303354746609564,
 'b4r2': 0.5297157622739018,
 'b7r10': 0.5293103448275862,
 'b4r4': 0.5283714075165807,
 'b6r4': 0.5283582089552239,
 'b8r5': 0.528125,
 'b10r10': 0.525027808676307,
 'b6r2': 0.5247524752475248,
 'b0r4': 0.5238095238095238,
 'b5r5': 0.5229357798165137,
 'b8r8': 0.5228215767634855,
 'b5r6': 0.520746887966805,
 'b4r1': 0.520671834625323,
 'b6r5': 0.5203426124197003,
 'b8r4': 0.5198237885462555,
 'b0r8': 0.5185185185185185,
 'b9r10': 0.5179856115107914,
 'b10r1': 0.5160965794768612,
 'b8r6': 0.5118790496760259,
 'b8r10': 0.5115646258503401,
 'b3r7': 0.5112285336856011,
 'b8r3': 0.5103969754253308,
 'b6r1': 0.5102040816326531,
 'b3r9': 0.5098039215686274,
 'b0r10': 0.5095890410958904,
 'b5r4': 0.5063613231552163,
 'b4r10': 0.5062344139650873,
 'b5r3': 0.5061511423550088,
 'b6r6': 0.5058430717863105,
 'b6r3': 0.5043156596794082,
 'b10r7': 0.5039840637450199,
 'b5r0': 0.5033557046979866,
 'b8r2': 0.5028409090909091,
 'b6r10': 0.5023923444976076,
 'b6r8': 0.5012224938875306,
 'b10r9': 0.4965986394557823,
 'b1r2': 0.4918793503480278,
 'b4r7': 0.4905897114178168,
 'b2r7': 0.48663101604278075,
 'b6r7': 0.48659003831417624,
 'b0r7': 0.4863636363636364,
 'b8r1': 0.48633879781420764,
 'b0r2': 0.483695652173913,
 'b0r3': 0.4828897338403042,
 'b5r10': 0.48174157303370785,
 'b5r2': 0.4810126582278481,
 'b9r3': 0.4807692307692308,
 'b4r9': 0.47619047619047616,
 'b5r7': 0.47480106100795755,
 'b9r4': 0.46853146853146854,
 'b0r1': 0.46703296703296704,
 'b8r0': 0.45454545454545453,
 'b8r7': 0.4543147208121827,
 'b9r6': 0.4396551724137931}

In [686]:
cluster_win_result_red = dict(sorted(cluster_win_result.items(), key=lambda item: item[1],reverse = False))
for key,value in cluster_win_result_red.items():
    cluster_win_result_red[key] = 1-value
cluster_win_result_red

{'b9r6': 0.5603448275862069,
 'b8r7': 0.5456852791878173,
 'b8r0': 0.5454545454545454,
 'b0r1': 0.532967032967033,
 'b9r4': 0.5314685314685315,
 'b5r7': 0.5251989389920424,
 'b4r9': 0.5238095238095238,
 'b9r3': 0.5192307692307692,
 'b5r2': 0.5189873417721519,
 'b5r10': 0.5182584269662922,
 'b0r3': 0.5171102661596958,
 'b0r2': 0.5163043478260869,
 'b8r1': 0.5136612021857924,
 'b0r7': 0.5136363636363637,
 'b6r7': 0.5134099616858238,
 'b2r7': 0.5133689839572193,
 'b4r7': 0.5094102885821832,
 'b1r2': 0.5081206496519721,
 'b10r9': 0.5034013605442177,
 'b6r8': 0.4987775061124694,
 'b6r10': 0.4976076555023924,
 'b8r2': 0.49715909090909094,
 'b5r0': 0.49664429530201337,
 'b10r7': 0.4960159362549801,
 'b6r3': 0.49568434032059183,
 'b6r6': 0.4941569282136895,
 'b5r3': 0.4938488576449912,
 'b4r10': 0.4937655860349127,
 'b5r4': 0.4936386768447837,
 'b0r10': 0.4904109589041096,
 'b3r9': 0.4901960784313726,
 'b6r1': 0.4897959183673469,
 'b8r3': 0.4896030245746692,
 'b3r7': 0.48877146631439894,
 'b8r10': 0.4884353741496599,
 'b8r6': 0.48812095032397407,
 'b10r1': 0.48390342052313884,
 'b9r10': 0.48201438848920863,
 'b0r8': 0.4814814814814815,
 'b8r4': 0.48017621145374445,
 'b6r5': 0.47965738758029974,
 'b4r1': 0.47932816537467704,
 'b5r6': 0.479253112033195,
 'b8r8': 0.4771784232365145,
 'b5r5': 0.47706422018348627,
 'b0r4': 0.47619047619047616,
 'b6r2': 0.4752475247524752,
 'b10r10': 0.47497219132369295,
 'b8r5': 0.47187500000000004,
 'b6r4': 0.4716417910447761,
 'b4r4': 0.47162859248341926,
 'b7r10': 0.4706896551724138,
 'b4r2': 0.4702842377260982,
 'b10r3': 0.46966452533904357,
 'b1r7': 0.46962616822429903,
 'b7r7': 0.4694656488549618,
 'b7r2': 0.4686907020872866,
 'b2r10': 0.46795646916565903,
 'b4r0': 0.46769230769230774,
 'b10r6': 0.4675740592473979,
 'b4r3': 0.46601146601146604,
 'b10r2': 0.46593406593406594,
 'b3r2': 0.4658119658119658,
 'b10r4': 0.46469002695417794,
 'b3r10': 0.4634986225895317,
 'b4r6': 0.4600389863547758,
 'b1r6': 0.46003262642740617,
 'b2r8': 0.45921450151057397,
 'b1r0': 0.4591836734693877,
 'b2r3': 0.4591836734693877,
 'b1r4': 0.4589774078478003,
 'b0r6': 0.4581673306772909,
 'b2r4': 0.4576043068640646,
 'b5r1': 0.4574780058651027,
 'b1r10': 0.4572025052192067,
 'b7r3': 0.4571428571428572,
 'b10r8': 0.45633187772925765,
 'b3r6': 0.4559748427672956,
 'b1r8': 0.4538258575197889,
 'b1r3': 0.4525316455696202,
 'b3r4': 0.45054151624548733,
 'b2r1': 0.45052083333333337,
 'b1r1': 0.4498069498069498,
 'b3r1': 0.44972067039106145,
 'b10r0': 0.44836956521739135,
 'b3r3': 0.4473140495867769,
 'b2r5': 0.4472222222222222,
 'b3r0': 0.44485294117647056,
 'b5r8': 0.4441176470588235,
 'b7r4': 0.44283121597096187,
 'b0r5': 0.44252873563218387,
 'b4r8': 0.44065281899109787,
 'b6r0': 0.43999999999999995,
 'b7r1': 0.43760984182776796,
 'b7r5': 0.437137330754352,
 'b7r6': 0.4327062228654125,
 'b4r5': 0.432258064516129,
 'b2r2': 0.43108504398826974,
 'b3r8': 0.42967542503863987,
 'b10r5': 0.4269406392694064,
 'b2r6': 0.4251012145748988,
 'b7r0': 0.423728813559322,
 'b3r5': 0.41751824817518246,
 'b1r5': 0.4012539184952978,
 'b7r8': 0.4003868471953579,
 'b2r0': 0.3933333333333333}

In [687]:
for i in range(11):
    print(f"The Champions in Cluster {i} are:", cluster10[cluster10['cluster']==i].index.values)

The Champions in Cluster 0 are: ['Jax' 'Graves' 'Kindred' 'Ekko' 'Tristana' 'Elise' 'Kalista' 'Camille'
 'Fiora' 'Tryndamere' 'Hecarim' 'Irelia' 'Riven' 'Gragas' 'Nidalee'
 "Kha'Zix"]
The Champions in Cluster 1 are: ['Sejuani' 'Pyke' 'Yasuo' 'Volibear' "Rek'Sai" 'Lee Sin' 'Olaf' 'Sona'
 'Anivia' 'Vi' 'Zac' 'Nocturne']
The Champions in Cluster 2 are: ['Ziggs' "Kog'Maw" 'Shyvana' 'Xerath' 'Ezreal' 'Heimerdinger' 'Illaoi'
 'Zyra' 'Karthus']
The Champions in Cluster 3 are: ['Trundle' 'Skarner' 'Leona' 'Ivern' 'Taric' 'Nami' 'Lulu' 'Jarvan IV'
 'Nautilus' 'Tahm Kench' 'Alistar' 'Thresh' 'Braum' 'Rakan']
The Champions in Cluster 4 are: ['Urgot' 'Poppy' 'Twisted Fate' 'Kled' 'Ornn' 'Sett' 'Renekton' 'Shen'
 'Darius' 'Sion' 'Galio' 'Zilean' 'Wukong' 'Pantheon' 'Fiddlesticks'
 'Aatrox' 'Malphite' 'Singed']
The Champions in Cluster 5 are: ["Cho'Gath" 'Veigar' 'Kayn' 'Fizz' 'Diana' 'Ahri' 'Cassiopeia' 'Talon'
 'Akali' 'Aurelion Sol' 'Yorick' 'Ryze' 'Yuumi' 'Kassadin' 'Qiyana'
 'Sylas']
The Champions in Cluster 6 are: ['Azir' 'Orianna' 'Evelynn' 'Maokai' 'Dr. Mundo' 'Neeko' 'Mordekaiser'
 'Zed' 'Malzahar' 'Lucian' 'Kayle' 'Gnar' 'Kennen' 'Lissandra']
The Champions in Cluster 7 are: ['Bard' 'Lux' 'Nunu & Willump' 'Xin Zhao' 'Garen' 'Morgana' 'Blitzcrank'
 'Karma' 'Janna' 'Soraka']
The Champions in Cluster 8 are: ['Jayce' 'Rumble' 'Swain' 'Viktor' 'Quinn' 'Corki' 'LeBlanc' "Vel'Koz"
 'Lillia' 'Taliyah' 'Gangplank' 'Zoe' 'Syndra' 'Vladimir' 'Senna']
The Champions in Cluster 9 are: ['Vayne' 'Draven' 'Caitlyn' 'Jinx' 'Jhin' 'Sivir' 'Aphelios'
 'Miss Fortune' "Kai'Sa" 'Ashe' 'Twitch' 'Xayah' 'Varus']
The Champions in Cluster 10 are: ['Teemo' 'Brand' 'Rengar' 'Rammus' 'Master Yi' 'Shaco' 'Warwick' 'Annie'
 'Amumu' 'Katarina']

## Cluster Prediction

In [739]:
df_bp_cluster = pd.read_csv("cluster_done20.csv")

In [741]:
# df_bp_cluster.sum().sort_values(ascending = False)[:10]

In [750]:
df_bp_cluster = df_bp_cluster.dropna()
y = df_bp_cluster['result']
X = df_bp_cluster.drop(columns = ['result','gameid'])
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1, shuffle = True)
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.2, random_state=1, shuffle = True)

In [751]:
X_train

,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,...,x33,x34,x35,x36,x37,x38,x39,x40,x41,x42
2614,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
5978,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4561,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3207,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3174,0.0,0.0,0.0,2.0,1.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5216,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
3837,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
5707,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3009,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2039,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

### SVM

In [752]:
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC

grid_c = {0.001:0,0.01:0,0.1:0,1:0,10:0,100:0,1000:0}
for c in grid_c.keys():
    svm = make_pipeline(StandardScaler(), SVC(gamma='auto',C = c, kernel = 'rbf'))
    svm.fit(X_train, y_train)
    prediction = list(map(round,svm.predict(X_val)))
    acc = accuracy_score(y_val, prediction)
    grid_c[c] = acc
dict(sorted(grid_c.items(), key=lambda item: item[1],reverse = True))

{100: 0.5235756385068763,
 1000: 0.5225933202357563,
 1: 0.5206286836935167,
 10: 0.5196463654223968,
 0.001: 0.5137524557956779,
 0.01: 0.5137524557956779,
 0.1: 0.5137524557956779}

In [753]:
prediction = list(map(round,svm.predict(X_test)))

cm = confusion_matrix(y_test, prediction)  
print ("Confusion Matrix : \n", cm)  
  
# accuracy score of the model 
print('Test accuracy = ', accuracy_score(y_test, prediction))

Confusion Matrix :
 [[284 287]
 [326 376]]
Test accuracy =  0.5184603299293009

### KNN

In [754]:
from sklearn.neighbors import KNeighborsClassifier
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1, shuffle = True)
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.2, random_state=1, shuffle = True)
grid_neigh = {i:0 for i in range(1,21)}
for key in grid_neigh.keys():
    neigh = make_pipeline(StandardScaler(), KNeighborsClassifier(n_neighbors=key))
    neigh.fit(X_train, y_train)
    prediction = list(map(round,neigh.predict(X_val)))
    acc = accuracy_score(y_val, prediction)
    grid_neigh[key] = acc
dict(sorted(grid_neigh.items(), key=lambda item: item[1],reverse = True))

{4: 0.5442043222003929,
 5: 0.5422396856581533,
 3: 0.5353634577603144,
 6: 0.5275049115913556,
 2: 0.5265225933202358,
 9: 0.5225933202357563,
 1: 0.5216110019646365,
 8: 0.5216110019646365,
 16: 0.5216110019646365,
 7: 0.5206286836935167,
 10: 0.5196463654223968,
 15: 0.5127701375245579,
 19: 0.5117878192534381,
 12: 0.5078585461689588,
 17: 0.5058939096267191,
 13: 0.5049115913555993,
 20: 0.5049115913555993,
 18: 0.5039292730844793,
 14: 0.5029469548133595,
 11: 0.4931237721021611}

In [755]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1, shuffle = True)

neigh = make_pipeline(StandardScaler(), KNeighborsClassifier(n_neighbors=5))
neigh.fit(X_train, y_train)
prediction = list(map(round,neigh.predict(X_test)))

cm = confusion_matrix(y_test, prediction)  
print ("Confusion Matrix : \n", cm)  
  
# accuracy score of the model 
print('Test accuracy = ', accuracy_score(y_test, prediction))

Confusion Matrix :
 [[264 307]
 [294 408]]
Test accuracy =  0.5278868813825609

### NN

In [756]:
from keras.models import Sequential
from keras.layers import Dense
from keras.callbacks import EarlyStopping
K.clear_session()
model = Sequential()
model.add(Dense(16, input_dim=X.shape[1], activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
# compile the keras model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
es = EarlyStopping(monitor='val_loss', mode='min', verbose=1,patience = 10)
# fit the keras model on the dataset
model.fit(X_train, y_train, epochs=50, batch_size=10,callbacks=[es],validation_split=0.2)
# evaluate the keras model
_, accuracy = model.evaluate(X_test, y_test)
print('Test Set Accuracy: %.2f' % (accuracy*100))

Epoch 1/50
408/408 [==============================] - 0s 1ms/step - loss: 0.6970 - accuracy: 0.5133 - val_loss: 0.6923 - val_accuracy: 0.5157
Epoch 2/50
408/408 [==============================] - 0s 879us/step - loss: 0.6901 - accuracy: 0.5427 - val_loss: 0.6935 - val_accuracy: 0.5128
Epoch 3/50
408/408 [==============================] - 0s 864us/step - loss: 0.6867 - accuracy: 0.5503 - val_loss: 0.6962 - val_accuracy: 0.5098
Epoch 4/50
408/408 [==============================] - 0s 884us/step - loss: 0.6838 - accuracy: 0.5670 - val_loss: 0.7000 - val_accuracy: 0.5039
Epoch 5/50
408/408 [==============================] - 0s 887us/step - loss: 0.6804 - accuracy: 0.5766 - val_loss: 0.7013 - val_accuracy: 0.5255
Epoch 6/50
408/408 [==============================] - 0s 876us/step - loss: 0.6769 - accuracy: 0.5837 - val_loss: 0.7027 - val_accuracy: 0.5079
Epoch 7/50
408/408 [==============================] - 0s 854us/step - loss: 0.6736 - accuracy: 0.5887 - val_loss: 0.7087 - val_accuracy: 0.5275
Epoch 8/50
408/408 [==============================] - 0s 855us/step - loss: 0.6697 - accuracy: 0.5955 - val_loss: 0.7082 - val_accuracy: 0.5049
Epoch 9/50
408/408 [==============================] - 0s 860us/step - loss: 0.6659 - accuracy: 0.6068 - val_loss: 0.7168 - val_accuracy: 0.4804
Epoch 10/50
408/408 [==============================] - 0s 880us/step - loss: 0.6629 - accuracy: 0.6049 - val_loss: 0.7229 - val_accuracy: 0.4666
Epoch 11/50
408/408 [==============================] - 0s 894us/step - loss: 0.6599 - accuracy: 0.6154 - val_loss: 0.7237 - val_accuracy: 0.5020
Epoch 00011: early stopping
40/40 [==============================] - 0s 521us/step - loss: 0.6970 - accuracy: 0.5617
Test Set Accuracy: 56.17

In [757]:
prediction = model.predict_classes(X_test)
cm = confusion_matrix(y_test, prediction) 
print ("Confusion Matrix : \n", cm)  
  
# accuracy score of the model 
print('Test accuracy = ', accuracy_score(y_test, prediction))

Confusion Matrix :
 [[241 330]
 [228 474]]
Test accuracy =  0.5616653574234093